### ISSUE TITLE
Support for bicepparam files

### ISSUE THREAD

**Issue by scottmckendry** [amaanq/tree-sitter-bicep#26]
bicepparam files are now the preffered over json parameter files for bicep deployments. 
[Docs](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/parameter-files?tabs=Bicep)

Can support for this file type be added to tree-sitter?

**Comment by scottmckendry** [comment]
Resolved using the autocmd here:
https://github.com/neovim/nvim-lspconfig/issues/2745#issuecomment-1676506505

**Comment by amaanq** [comment]
Just saw this, this should be PRed to vim and then backported to neovim

**Comment by scottmckendry** [comment]
Thanks for the pointer. PR has been opened:
https://github.com/vim/vim/pull/12784
