### ISSUE TITLE
Improve support for bicepparam files

### ISSUE THREAD

**Issue by josteink** [amaanq/tree-sitter-bicep#30]
Most `bicepparam`-files start with importing the module whose parameters they are populating.

https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/parameter-files?tabs=Bicep#parameters-file

````bicep
using 'main.bicep'

param storageName = toLower('MyStorageAccount')
param intValue = 2 + 2
````

Using the latest language-garammer, the `using` statement is reported as a grammatical-error, meaning all valid `bicepparam`-files will show having errors in the editor.

I haven't really looked into extending tree-sitter grammars before (only consuming them), so no idea if this is hard to fix or not.

**Comment by amaanq** [comment]
There is support for `using` now, as well as a plethora of changes, thanks for the bug report. Let me know of other issues.
